### ISSUE TITLE
About LSTM::forward

### ISSUE THREAD

**Issue by tonyguo1987** [hassyGo/N3LP#1]
I have a question about the calculation in LSTM::forward. 
In your implementation, each gate is calculated as follows:

 cur->i = this->bi + this->Wxi_xt + this->Whi_prev->h;
where there are 2 summations, current x and previous h. 

But in most papers I read, for example this: ftp://ftp.idsia.ch/pub/juergen/nn_2005.pdf (page 7)
and [this](http://www.cs.toronto.edu/~graves/preprint.pdf) (page 46),
each gate consists of 3 summations, which are current x, previous h and previous cell state (c in your implementation). 

Could you tell me why cur->i is not added by previous cell state (c) ?

**Comment by hassyGo** [comment]
Hi, thank you for the question and sorry for the absent of any citations.
You are right; previous cell states are used to compute input and forget gates in most papers, but some papers, for example [1, 2], employ a variant of the major way of the LSTM's gate computation.
My implementation is following the simplified version.
I should have put the citations.

Thanks again,

[1] http://arxiv.org/abs/1410.4615
[2] http://nlp.stanford.edu/pubs/tai-socher-manning-acl2015.pdf

**Comment by tonyguo1987** [comment]
Thank you very much for your answer!
It is very helpful.
