### ISSUE TITLE
Compiling on Mac OSX Yosemite

### ISSUE THREAD

**Issue by xuanchien** [hassyGo/N3LP#2]
I am trying to compile this on Mac OSX Yosemite but I keep getting an error about `omp.h` file. I googled and found some suggestion to use different g++ version instead of the default on Mac, but even if I use g++-4.9 or g++-6, it still does not work.

Error message when using default g++:

```
g++ -c  -O3 -std=c++0x -lm -funroll-loops -march=native -m64 -DEIGEN_DONT_PARALLELIZE -DEIGEN_NO_DEBUG -DEIGEN_NO_STATIC_ASSERT -I$HOME/tools/eigen  -fopenmp -o objs/EncDec.o EncDec.cpp
clang: warning: -lm: 'linker' input unused
EncDec.cpp:6:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [objs/EncDec.o] Error 1
```

Error message when using g++-6:

```
Utils.hpp: In function 'void Utils::infNan(const Real&)':
Utils.hpp:69:19: error: invalid initialization of reference of type 'const Eigen::half&' from expression of type 'const Real {aka const double}'
     assert(!isnan(x) && !isinf(x));
                   ^
In file included from /Users/nguyenlab-imac/tools/eigen/Eigen/Core:356:0,
                 from Matrix.hpp:3,
                 from LSTM.hpp:3,
                 from EncDec.hpp:3,
                 from EncDec.cpp:1:
```

Do you know how to fix this issue?

**Comment by hassyGo** [comment]
Thank you very much for being interested in our codes and pointing out the issue. I will investigate how to resolve it and report the solution. I've never seen such a compile error shown in the second one. By the way, one quick suggestion is that you could avoid the issue by not using clang.

**Comment by xuanchien** [comment]
@hassyGo Thanks for your quick response. I installed g++-6 (`brew install gcc --without-multilib`) but it does not resolve the issue.

How to avoid using clang in this case? I thought g++-6 is not clang, right?

**Comment by xuanchien** [comment]
I managed to fix this issue by using `clang-omp++` as the default compiler. Modify `Makefile` and change the first line to:

`CXX=clang-omp++`

It would be great if we can detect OS and use correct compiler accordingly for each OS.

**Comment by hassyGo** [comment]
Great! Thank you very much for your help. As a quick solution, I just added the compiler in comment in Makefile, and updated README.

Now the new version of Eigen is available, so we will also update Makefile to better use the new features!

**Comment by exbracer** [comment]
You can fix that bug by adding code in Utils.hpp like this
`Eigen::half temp_x = (Eigen::half)x;
assert(!isnan(temp_x) && !isinf(temp_x));`

Actually this bug happens not only in Mac OS but also in Ubuntu. I think it is caused by the version of the compiler. The type conversion should be don explicitly, maybe.
